ablation:
  tag: "run"
  config_file: "conf.yaml"
  script_file: "demo_train_script.py"
  is: true
  count: 2
  opts:
    training:
      batch_size: [4,8]
      num_workers: [2,3]

#  opts: ['training:batch_size', 'training:num_workers']
base:
  gpus: "0,1,2,3"
  base_dir: './debug_runs/'
  experiment: "ablation"
  tag: layer_test1 # lr_test / threshold
# tag: 'notag'
