base_dir: ../runs-3d/
dataset:
  clip:
  - -200.0
  - 400.0
  pth: /home1/quanquan/datasets/Head-and-Neck-challenge/preprocessed/
new_dict:
  aa: 1
  bb: 2
new_dict2:
  test: test
  test2: test2
optim:
  decay_gamma: 0.8
  decay_step: 50
  learning_rate: 0.0001
  weight_decay: 0.0001
special:
  alpha: 0.99
  emb_len: 32
  nearby: 24
  num_landmarks: 6
tag: notag
testing:
  LABEL_CONFIG:
    labels:
      BrainStem: null
      Mandible: null
      Parotid_L: null
      Parotid_R: null
  batch_size: 1
  epoch: 1
  label_name: Mandible
training:
  batch_size: 8
  crop_size:
  - 128
  - 128
  - 64
  num_epochs: 12800
  num_workers: 8
  patch_size:
  - 64
  - 64
  - 32
  save_seq: 10
