__INFO__:
  Argv: 'Argv: train_ablation.py'
  logger: text_only
  runtime: 2021-08-22-05:33:24.105123
ablation:
  config_file: conf.yaml
  count: 2
  is: true
  opts:
    training:
      batch_size:
      - 4
      - 8
      num_workers:
      - 2
      - 3
  script_file: demo_train_script.py
  tag: ablation_test
base_dir: ./debug_runs/
config: ablation.yaml
extag: ''
gpus: 0,1,2,3
runs_dir: ./debug_runs/2021-08-22-05:33:24.105110
stage: ''
tag: 2021-08-22-05:33:24.105110
test: false
