#
# python ablation_trainer.py --config configs/ablation.config

base:
  base_dir: '../runs-3d/'
  tag: 'notag'
  runs_dir: '../runs-3d/'

ablation:
  is: true
  opts: ['training:batch_size', 'training:num_workers']

dataset:
  pth: '/home1/quanquan/datasets/Head-and-Neck-challenge/data/'
training:
  batch_size : 4
  num_workers : 4
  num_epochs : 1280
  save_seq : 50
  crop_size: (96,96,64)
  patch_size: (96,96,64)
optim:
  learning_rate: 0.00001
  weight_decay: 0.0001
  decay_step: 50
  decay_gamma: 0.8

# Task-specific params
special:
  num_landmarks : 19
  emb_len: 32
  nearby : 6
  alpha: 0.99
#  lambda : 2
#  non_local: True
#  conf: False

# Testing
testing:
  epoch: 1
  batch_size: 1