__INFO__:
  Argv: 'Argv: demo_train_script.py --tag abla1/ablation_test_iter_1 --config _tmp_config.yaml'
  logger: text_only
  runtime: 2021-08-22-05:34:13.108714
ablation:
  is: true
  opts:
  - training:batch_size
  - training:num_workers
base_dir: ./debug_runs/
config: _tmp_config.yaml
dataset:
  clip:
  - -200.0
  - 400.0
  pth: /home1/quanquan/datasets/Head-and-Neck-challenge/preprocessed/
extag: ''
optim:
  decay_gamma: 0.8
  decay_step: 50
  learning_rate: 0.0001
  weight_decay: 0.0001
runs_dir: ./debug_runs/abla1/ablation_test_iter_1
special:
  alpha: 0.99
  emb_len: 32
  nearby: 24
  num_landmarks: 6
stage: ''
tag: abla1/ablation_test_iter_1
test: false
testing:
  LABEL_CONFIG:
    labels:
      BrainStem: null
      Mandible: null
      Parotid_L: null
      Parotid_R: null
  batch_size: 1
  epoch: 1
  label_name: Mandible
training:
  batch_size: 8
  num_workers: 3
